---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/signup":
    post:
      summary: create user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                  id:
                    type: integer
                example:
                  user:
                    email: natasha@example.com
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: string
                properties:
                  error: string
                example:
                  error: Email can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: user keys returned after user creation
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              example:
                user:
                  email: natasha@example.com
                  password: password
              required:
              - email
              - password
definitions:
  user:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
