defaults: &defaults
  SMS_PROVIDER: your_sms_provider_url
  SMS_CALLBACK_DOMAIN: your_sms_callback_domain
  JWT_SECRET: your_jwt_secret_key

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
