default: &default
  SMS_PROVIDER: your_sms_provider_url
  SMS_CALLBACK_DOMAIN: your_sms_callback_domain
  JWT_SECRET: your_jwt_secret_key
  DOMAIN: localhost:3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
